### ISSUE TITLE
テストケースを増やす

### ISSUE THREAD

**Issue by TakayukiKawajiri** [MIERUNE/japan-mesh-tool#16]
できれば、４７都道府県の県庁所在地をチェック
https://www.stat.go.jp/data/mesh/pdf/gaiyo1.pdf

**Comment by bordoray** [comment]
Add places details
![image](https://github.com/MIERUNE/japan-mesh-tool/assets/26103833/ffc7adf4-16cc-42ac-b2c1-b23514a37a8f)

**Comment by TakayukiKawajiri** [comment]
テストケースのXY計算用
https://docs.google.com/spreadsheets/d/1eN9vLibIuwKIllkWjjvHrUvTdvrjknqZHQQsQrL1acc/edit#gid=1226158102

**Comment by TakayukiKawajiri** [comment]
４次、７次も追加しましょう
