### ISSUE TITLE
Incorrect Mesh code of the Secondary Area Partition

### ISSUE THREAD

**Issue by pinksilverdrop** [MIERUNE/japan-mesh-tool#8]
Thank you for making this package. I tried to get the output of the Secondary Area Partition with the python command and found what I think a bug.

**Command Sample**
`python python/japanmesh/main.py 2 -e 134.7510,33.1147 137.7196,37.9844`

**Problem description**
In the case when either or both of the last 2-digits is greater than or equal to 5, the first 4-digit number that indicates the Primary Area Partition seems incorrect.

![5236](https://user-images.githubusercontent.com/67534824/222950062-595ea3e0-f611-46fb-af01-04875e57af58.PNG)

**Expected Output**
Please refer to the link: [全国標準地域メッシュ２次メッシュ（約10㎞四方）](https://www.geospatial.jp/ckan/dataset/biodic-mesh/resource/8cc999b5-82d9-46e0-8eb8-f4fc7ab2612e)

**Comment by yayayagi721** [comment]
found a solution.
It seems to be incremented if the decimal point is more than 0.5.
https://github.com/MIERUNE/japan-mesh-tool/blob/d44b6cd82e5fdc1cae1df42a8fd773a7f8289f73/python/japanmesh/main.py#L188

change it to the code below, it outputs the correct mesh code
```
"code": str(math.floor(bottom_lat * 1.5)) + str(math.floor(left_lon))[1:] + get_meshcode(meshnum, x, y)
```

**Comment by pinksilverdrop** [comment]
Thank you for helping me. It works as expected in the range of mesh code 5236.

However, it seems incorrect when the latitude of the south edge of a grid square becomes an infinite decimal. The same problem occurs in other types of area partition, not limited to the Secondary Area Partition. 

An example is shown below. 
(The latitude of the south edge of mesh code 5336 is 35.33333333333333.)

![5336](https://user-images.githubusercontent.com/67534824/229032393-f8841a2f-a5b2-4643-bd07-7f3b0586d2cc.PNG)

Therefore I just added a tiny number to the latitude of the south edge of a grid square before rounding down, and it works as I expected.
```
"code": str(int(bottom_lat * 1.5 + 1.0e-10)) + str(int(left_lon))[1:] + get_meshcode(meshnum, x, y)
```

![5336_modified](https://user-images.githubusercontent.com/67534824/229032484-45ba29df-f32c-4be8-aef7-713b8d30085c.PNG)

**Comment by yayayagi721** [comment]
@pinksilverdrop 
thank you! It will help.
